
[bell]
animation = "EaseOutCirc"
color = "0x555555"
duration = 100

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0xeaeaea"
yellow = "0xe6c547"

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 11.0
normal.family = "Fira Code"
bold.style = "Bold"
italic.style = "Italic"
offset = {x = 0, y = 0}

[mouse]
hide_when_typing = false
bindings = [
    {action = "PasteSelection", mouse = "Middle"}
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
dynamic_padding = false
padding = {x = 2, y = 2}

[general]
live_config_reload = true
